version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Managed dependencies
          command: |
            python -m venv venv
            . venv/Script/activate
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
      - run:
          name: Lint
          command: python -m flake8
      - run:
          name: Tests
          command: python -m pytest


workflows:
  complete_deploy:
    jobs:
      - build
