version: 2.1

jobs:
  build:
    docker:
      - image: sebastiengiordano/oc_lettings_site
        auth:
          username: $DOCKER_ID
          password: $DOCKER_PWD
    steps:
      - checkout
      - run:
          name: Managed dependencies
          command: echo 'Hello World!'


workflows:
  version: 2.1
  test_build_job:
    jobs:
      - build:
          context:
            - docker-env-var
