# CircleCI configuration file
version: 2.1


jobs:
    build-and-test:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - python/install-packages:
                pkg-manager: pip
            - run:
                name: Lint
                command: flake8
            - run:
                name: Run tests
                command: pytest
