version: 2.1

jobs:
  build-and-test:
    docker:
      - image: sebastiengiordano/oc_lettings_site
        auth:
          username: $DOCKER_ID
          password: $DOCKER_PWD
    steps:
      - checkout
      - python/install-packages:
        pkg-manager: pip
      - run
        name: Lint
        command: python -m flake8
      - run:
        name: Run tests
        command: python -m pytest


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-and-test:
          context:
            - docker-env-var
