version: 2.1

jobs:
  build:
    docker:
      - image: sebastiengiordano/oc_lettings_site/python:3.9
        auth:
          username: $DOCKER_ID
          password: $DOCKER_PWD
    steps:
      - checkout
      - run:
          name: Managed dependencies
          command: echo 'Hello World!'


workflows:
    jobs:
      - build:
          context:
            - docker-env-var