version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Managed dependencies
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'


workflows:
  complete_deploy:
    jobs:
      - build
