version: 2.1

jobs:
  build:
    docker:
      - image: sebastiengiordano/oc_lettings_site/python:3.9
    steps:
      - checkout
      - run:
          name: Managed dependencies
          command: echo 'Hello World!'
